### PR TITLE
backward compatibility for caching done with old pandas indices

### PR DESCRIPTION
**Pull request by p-mc-grath**

### CODE REVIEW

**Comment by mschrimpf** [comment]
can you please add more explanation of what this solves?

**Comment by p-mc-grath** [comment]
I encountered FrozenIndices Error trying to load a pandas dataframe after updating my pandas version. This commit introduces backward compatibility, i.e. you are fine if you pickle.dump() using an old pandas' version and trying to load using a new pandas' version.

see https://github.com/pandas-dev/pandas/issues/34535

**Comment by mschrimpf** [comment]
would this still work (or raise explanatory exceptions) when loading a pickle file that is not a pandas object?

**Comment by p-mc-grath** [comment]
[Official documentation of pd.read_pickle()](https://pandas.pydata.org/docs/reference/api/pandas.read_pickle.html) says: 
"pandas.read_pickle(filepath_or_buffer, compression='infer', storage_options=None)
Load pickled pandas object (or any object) from file."

So it should, do you want me to double-check?

**Comment by mschrimpf** [comment]
all good, that sounds fine

**Review by mschrimpf — APPROVED** [review]

**Comment by mschrimpf** [comment]
had to revert this (#12), `catch` is not python syntax. I guess this highlights the need for unit tests in this repository :)

**Comment by p-mc-grath** [comment]
Corrected in #13

**Pull request merged**
